[package]
name = "eth-sparse-mpt"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
alloy-primitives = { version = "0.7.4", features = ["asm-keccak", "serde"] }
alloy-rlp = "0.3.5"
alloy-trie = "0.4.1"
eyre = "0.6.12"
hash-db = "0.15.2"
thiserror = "1.0.61"
triehash = "0.8.4"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
proptest = "1.4.0"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "trie_insert_bench"
harness = false
